config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "/top-artists", to: "pages#top_artists", as: :top_artists
  get "/home", to: "pages#home", as: :home
  get "/view-profile", to: "pages#view_profile", as: :view_profile
  get "/clear", to: "pages#clear", as: :clear
  get "/listening-patterns", to: "listening_patterns#hourly", as: :listening_patterns
  get "/listening-monthly", to: "listening_patterns#monthly", as: :listening_monthly
  get "/mood-explorer", to: "pages#mood_explorer"
  get "/mood-analysis/:id", to: "pages#mood_analysis", as: :mood_analysis
  get "/listening-heatmap", to: "listening_patterns#calendar", as: :listening_heatmap
  get "/playlists/:id/energy", to: "pages#playlist_energy", as: :playlist_energy
  resources :playlists, only: [] do
    collection do
      get :compare_form
      get :compare
    end
  end
  get "/personality", to: "personality#show", as: :personality
  root "pages#home"

  # Callback from Spotify
  match "/auth/spotify/callback", to: "sessions#create", via: %i[get post]
  get    "/auth/failure",         to: "sessions#failure"
  get    "/login",                to: redirect("/auth/spotify"), as: :login
  delete "/logout", to: "sessions#destroy", as: :logout

  resources :artist_follows, only: [ :create, :destroy ], param: :spotify_id

  # GET /top_tracks
  get "/top_tracks", to: "top_tracks#index", as: :top_tracks
  post "/create_playlist", to: "playlists#create", as: :create_playlist

  # Get Recommendations
  get  "recommendations",        to: "recommendations#recommendations",   as: :recommendations

  get "/search", to: "search#index", as: :search
  get "/playlist_genres", to: "playlist_genres#index", as: :playlist_genres_index

  get "/playlists/:id/genres", to: "playlist_genres#show", as: :playlist_genres
  post "/playlists/:id/split_by_genre", to: "playlist_genres#split", as: :split_playlist_by_genre

  get "/stories/:playlist_id", to: "stories#show", as: :stories
  get "/wrapped", to: "wrapped#index", as: :wrapped
end

app/views/layouts/_navbar.html.erb
<%= link_to "Playlists", playlists_path,
      class: "nav-link #{'active' if current_page?(playlists_path)}" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_importmap_tags %>
    <%= yield :extra_css %>

    <script>
      document.documentElement.classList.add('js');
    </script>
  </head>

  <body class="no-js">
    <header>
      <nav class="spotify-nav d-flex align-items-center justify-content-between px-3">
        <!-- Left-aligned nav links -->
        <div class="nav-left d-flex">
          <a class="nav-logo" href="<%= home_path %>">
            <%= image_tag "spotilytics-logo-white.png",
                          alt: "Spotilytics Logo",
                          class: "nav-bar-logo" %>
          </a>
          <%= link_to 'Home', home_path,
                      class: "nav-link #{'active' if (current_page?(home_path) || current_page?(root_path))}" %>

          <% if session[:spotify_user] %>
            <%= link_to 'Dashboard', dashboard_path,
                        class: "nav-link #{'active' if current_page?(dashboard_path)}" %>
            <%= link_to "Top Tracks", top_tracks_path,
                        class: "nav-link #{'active' if current_page?(top_tracks_path)}" %>
            <%= link_to "Top Artists", top_artists_path,
                        class: "nav-link #{'active' if current_page?(top_artists_path)}" %>
            <%= link_to "Listening Pattern", listening_patterns_path,
                        class: "nav-link #{'active' if current_page?(listening_patterns_path)}" %>
            <%= link_to "Monthly Hours", listening_monthly_path,
                        class: "nav-link #{'active' if current_page?(listening_monthly_path)}" %>
            <%= link_to "Listening Heatmap", listening_heatmap_path, class: "nav-link #{'active' if current_page?(listening_heatmap_path)}" %>
            <%= link_to "Personality", personality_path, class: "nav-link #{'active' if current_page?(personality_path)}" %>
            <%= link_to "Compare Playlists", compare_form_playlists_path,
                        class: "nav-link #{'active' if current_page?(compare_form_playlists_path)}" %>
            <%= link_to "Discover", recommendations_path,
                        class: "nav-link #{'active' if current_page?(recommendations_path)}" %>
            <%= link_to "Wrapped", wrapped_path,
            class: "nav-link #{'active' if current_page?(wrapped_path)}" %>

            <div class="nav-search-wrapper">
              <%= form_with url: search_path, method: :get, local: true, class: "navbar-search-form" do %>
                <input
                  type="text"
                  name="query"
                  placeholder="Search for songs, artists, albums..."
                  class="navbar-search-input"
                  value="<%= h(params[:query] || params[:q]) %>"
                  autocomplete="off"
                >
              <% end %>
            </div>
            <%= link_to "Genre Breakdown", playlist_genres_index_path,
            class: "nav-link #{'active' if current_page?(playlist_genres_index_path)}" %>

            
          <% end %>
        </div>

        <!-- Right-aligned user links -->
        <div class="nav-right d-flex">
          <% if session[:spotify_user] %>
            <%= link_to 'Refresh Data', clear_path, class: "refresh-button" %>
            <%= link_to view_profile_path,
                        class: "nav-link #{'active' if current_page?(view_profile_path)}",
                        rel: "noopener noreferrer" do %>
              <p style="margin-bottom: 0 !important;">
                Logged in as
                <strong><%= current_user['display_name'] || current_user['email'] %></strong>
              </p>
            <% end %>
            <%= button_to "Log out", logout_path, method: :delete, class: "nav-link" %>
          <% else %>
            <%= link_to 'Login with Spotify', "/auth/spotify", class: 'nav-link' %>
          <% end %>
        </div>
      </nav>
    </header>

    <% if notice.present? || alert.present? %>
      <div class="flash-div">
        <% if notice.present? %>
          <p class="flash flash-notice spotify-notice"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p class="flash flash-alert spotify-alert"><%= alert %></p>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>